name: AndroidLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - .github/workflows/android-lint.yml
      - '*/src/**'
      - gradle/**
      - '**.gradle'
      - gradle.properties
      - gradlew*

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - run: ./gradlew lint

      - name: Upload html test report
        uses: actions/upload-artifact@v4
        with:
          name: lint.zip
          path: composeApp/build/reports/lint-results-debug.html
  unit-test:
    needs: [android-lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle

      - name: Run tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: index.zip
          path: composeApp/build/reports/tests/testDebugUnitTest/
  build_app:
    needs: [unit-test]
    name: Building app
    runs-on: macos-latest
#    env:
#      API_KEY: ${{ secrets.API_KEY }}
#      REVENUECAT_API_KEY_ANDROID: ${{ secrets.REVENUECAT_API_KEY_ANDROID }}
#      REVENUECAT_API_KEY_IOS: ${{ secrets.REVENUECAT_API_KEY_IOS }}

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: actions/cache@v4
        with:
          path: /Users/runner/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build Android Debug app
        run: ./gradlew assembleDebug

#      - name: Build iOS Debug app
#        run: xcodebuild -allowProvisioningUpdates -workspace iosApp/iosApp.xcodeproj/iosApp.xcworkspace -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 14' build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: composeApp/build/outputs/apk/debug/**.apk
